site_name: "Paul Pénicaud-Desury"
nav:
    - Accueil: index.md
    - "Expériences": experiences.md
    - "Compétences professionnelles": competences.md
#    - "À propos": about.md
    - Veille: Veille.md

theme:
    name: readthedocs
    locale: fr
    color_mode: light
    user_color_mode_toggle: true
